name: check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run deno lint
        run: deno lint --unstable

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest deno version
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run deno fmt
        run: deno fmt --check

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v2
#
#      - name: Setup latest deno version
#        uses: denoland/setup-deno@main
#        with:
#          deno-version: v1.x
#
#      - name: Run deno test
#        run: deno test --allow-all --unstable

#  doc:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v2
#
#      - name: Setup latest deno version
#        uses: denoland/setup-deno@main
#        with:
#          deno-version: v1.x
#
#      - name: Run deno test --doc
#        run: deno test --allow-all --unstable --doc --import-map import_map.json
